### PR TITLE
Pattern panel scrollbars

### PR DESCRIPTION
**Pull request by jean-emmanuel**
- the mainwid object is wrapped in a Layout and 2 Boxes (one for each scrollbar, I tried with a Table but I didn't behave well with fill/expand/shrink options 
- the bottom bar is now fixed to the bottom of the window, it looks better when resized
- scrollbar autohide :-)
- the mainwnd object explicilty requires a size based on its contents' at init, otherwise it would jump to its natural size when the scrollbars appear / disappear

### CODE REVIEW

**Comment by ahlstromcj** [comment]
I have checked in your code, modified to fix some compiler errors and to add the status of your feature to the "./Seq64rtmidi/seq64 --version" command.  When I run it, I see the feature is enabled, but there are no scrollbars.  So I think you may have more changes to add?  Please pull the latest wip and see what you think.  Note the new feature macro set up in configure.ac, so be sure to do a "./bootstrap --full-clean" before you rebuild.  Thanks!

**Comment by jean-emmanuel** [comment]
Have you tried to resize window ? I'll test that soon !

**Comment by jean-emmanuel** [comment]
It works like a charm here ;), scrollbars are not visible unless the pattern doesn't fit in the window.

**Comment by ahlstromcj** [comment]
I cannot resize the window.  (I use the Fluxbox window manager, I'll try it with xfce just to see.)

If you want to diff wip and your stuff, you can add anything that missing to wip if you want to.  I could be I messed something up while annotating the code.

I suppose I could checkout your branch, too.

**Comment by ahlstromcj** [comment]
Check out the multimainwid branch!  In the root is a screenshot of this mode showing the maximum number of sets at once.  You can build the branch and get that view by running it from the command line: "./Seq64rtmidi/seq64 -o set-rows=3 -o set-columns=2".  That's the max size so far, but we could later allow larger values and use a variation on your scroll-bar feature.  Try running that command and loading the file "contrib/midi/b4uacuse-stress.midi".  It seems to play, too, though I didn't try it with sound.  There is still a bit to do, like get the active set to be highlight, add arbitrary set spinners to each grid, and get the overall set spinner to work (to show and set the active set).

Let me know what you think.  I'm kind of happy with it already.

**Comment by jean-emmanuel** [comment]
See https://github.com/ahlstromcj/sequencer64/pull/84 for fixing pattern panel scrollbar (my window manager can resize anything, it made me miss that caveat).

**Pull request merged**
